spring:
  datasource:
    url: jdbc:sqlite:file:./src/main/resources/db/Chinook.db
    driver-class-name: org.sqlite.JDBC
  mvc:
    async:
        request-timeout: 120000
  sql:
    init:
      mode: never

server:
  tomcat:
    connection-timeout: 120s


