spring:
  config:
    active:
      on-profile: spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b-instruct
        options:
          num-predict: 1024